create view exp_view_lek(kod, name) as
SELECT DISTINCT exp_std_prep.kod,
                exp_std_prep.name
FROM exp_std_prep;

alter table exp_view_lek
    owner to exp_user;

INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Тикагрелор');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AB', 'Эсмолол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AX', 'Эзетимиб');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C03CA', 'Фуросемид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Ацетилсалициловая кислота + Клопидогрел');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A03FA', 'Метоклопрамид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AB', 'Гепарин натрия');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A10AB', 'Инсулин растворимый [человеческий генно-инженерный]');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B03XA', 'Дарбэпоэтин альфа');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BC', 'Эзомепразол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AD', 'Алтеплаза');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01XA', 'Ванкомицин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AB', 'Метопролол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Каптоприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05BA', 'Диазепам');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Зофеноприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B05CX', 'Декстроза');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AX', 'Ривароксабан');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01DH', 'Имипенем + [Циластатин]');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V08AB', 'Йопромид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01CA', 'Норэпинефрин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AB', 'Бисопролол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('D08AX', 'Этанол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AD', 'Стрептокиназа');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('R06AC', 'Хлоропирамин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Эптифибатид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V03AB', 'Налоксон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B03AC', 'Железа [III] гидроксида сахарозный комплекс');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Рамиприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('D08AG', 'Повидон-Йод');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C03AA', 'Гидрохлоротиазид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05AD', 'Дроперидол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01BA', 'Прокаинамид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Лизиноприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AB', 'Эноксапарин натрия');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AA', 'Аторвастатин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01CA', 'Добутамин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AA', 'Симвастатин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09CA', 'Валсартан');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AE', 'Бивалирудин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A09AA', 'Панкреатин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B05XA', 'Натрия хлорид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01AA', 'Доксициклин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A10BB', 'Глибенкламид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01FA', 'Азитромицин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AX', 'Эволокумаб');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A07FA', 'Бифидобактерии бифидум');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Антител моноклональных FRaMon F[ab'']2-фрагменты');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01DD', 'Цефоперазон + [Сульбактам]');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J02AC', 'Флуконазол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C08CA', 'Амлодипин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05AD', 'Галоперидол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V08AB', 'Йодиксанол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AG', 'Карведилол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01CA', 'Допамин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01BB', 'Лидокаин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01DA', 'Изосорбида динитрат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Прасугрел');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C03DA', 'Спиронолактон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('M01AB', 'Диклофенак');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AF', 'Ривароксабан');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01DD', 'Цефтриаксон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BA', 'Ранитидин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05BA', 'Бромдигидрохлорфенилбензодиазепин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AA', 'Пропранолол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C03DA', 'Эплеренон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BC', 'Омепразол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AA', 'Розувастатин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J02AC', 'Вориконазол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01DD', 'Цефтазидим');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A12CX', 'Калия и магния аспарагинат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B03AB', 'Железа [III] гидроксид полимальтозат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05BA', 'Оксазепам');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AD', 'Проурокиназа');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01DA', 'Изосорбидадинитрат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A10BB', 'Глимепирид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01CA', 'Эпинефрин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N06AB', 'Сертралин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BA', 'Фамотидин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N01AH', 'Фентанил');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Периндоприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C08DB', 'Дилтиазем');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01FA', 'Кларитромицин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B05AA', 'Декстран');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C10AX', 'Алирокумаб');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A10BA', 'Метформин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A12BA', 'Калия хлорид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AA', 'Варфарин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01BD', 'Амиодарон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N03AE', 'Клоназепам');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Ацетилсалициловая кислота');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A03BA', 'Атропин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01DA', 'Изосорбида мононитрат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Эналаприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N02AA', 'Морфин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C08DA', 'Верапамил');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V03AB', 'Протамина сульфат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01DA', 'Нитроглицерин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C09AA', 'Трандолаприл');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01CR', 'Амоксициллин + [Клавулановая кислота]');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B02AB', 'Апротинин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B05XA', 'Натрия гидрокарбонат');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V08AB', 'Йогексол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BC', 'Рабепразол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C07AA', 'Соталол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Клопидогрел');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AD', 'Тенектеплаза');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('D07AA', 'Преднизолон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N05AL', 'Сульпирид');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('H02AB', 'Дексаметазон');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AX', 'Фондапаринукс натрия');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('V08AB', 'Йоверсол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('A02BC', 'Пантопразол');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('N06AB', 'Пароксетин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B05BA', 'Аминокислоты для парентерального питания');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('B01AC', 'Монафрам');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C01AA', 'Дигоксин');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('J01DH', 'Меропенем');
INSERT INTO public.exp_view_lek (kod, name) VALUES ('C03CA', 'Торасемид');