create view exp_view_usl(id, usl_code, name, rel, enable) as
SELECT exp_usl.id,
       exp_usl.usl_code,
       exp_usl.name,
       exp_usl.rel,
       exp_usl.enable
FROM exp_usl
WHERE (EXISTS(SELECT 1
              FROM exp_std_usl
              WHERE exp_std_usl.kod_usl::text = exp_usl.usl_code::text));

alter table exp_view_usl
    owner to exp_user;

INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1550, 'A04.28.001', 'Ультразвуковое исследование почек и надпочечников', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1603, 'A05.10.004', 'Расшифровка, описание и интерпретация электрокардиографических данных', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1605, 'A05.10.006', 'Регистрация электрокардиограммы', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1609, 'A05.10.008', 'Холтеровское мониторирование сердечного ритма', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1612, 'A05.10.009.001', 'Магнитно-резонансная томография сердца с контрастированием', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1643, 'A05.23.009', 'Магнитно-резонансная томография головного мозга', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1711, 'A06.03.002', 'Компьютерная томография лицевого отдела черепа', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1850, 'A06.09.007', 'Рентгенография легких', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1851, 'A06.09.007.001', 'Прицельная рентгенография органов грудной клетки', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1860, 'A06.10.006', 'Коронарография', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1862, 'A06.10.008', 'Вентрикулография сердца', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2028, 'A06.30.005', 'Компьютерная томография органов брюшной полости', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2093, 'A07.10.001', 'Сцинтиграфия миокарда', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1384, 'A03.16.001', 'Эзофагогастродуоденоскопия', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1399, 'A03.19.002', 'Ректороманоскопия', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1475, 'A04.10.002', 'Эхокардиография', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1476, 'A04.10.002.001', 'Эхокардиография чреспищеводная', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1478, 'A04.10.002.003', 'Эхокардиография с фармакологической нагрузкой', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1479, 'A04.10.002.004', 'Эхокардиография с физической нагрузкой', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1484, 'A04.12.001.002', 'Дуплексное сканирование артерий почек', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1496, 'A04.12.004', 'Внутрисосудистое ультразвуковое исследование сосудистой стенки', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1497, 'A04.12.005', 'Дуплексное сканирование сосудов (артерий и вен) верхних конечностей', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1500, 'A04.12.005.003', 'Дуплексное сканирование брахиоцефальных артерий с цветным допплеровским картированием кровотока', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1501, 'A04.12.006', 'Дуплексное сканирование сосудов (артерий и вен) нижних конечностей', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1515, 'A04.14.001', 'Ультразвуковое исследование печени', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (1522, 'A04.15.001', 'Ультразвуковое исследование поджелудочной железы', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2417, 'A09.05.009', 'Исследование уровня С-реактивного белка в сыворотке крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2426, 'A09.05.018', 'Исследование уровня мочевой кислоты в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2434, 'A09.05.023.002', 'Дистанционное наблюдение за показателями уровня глюкозы крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2456, 'A09.05.037', 'Исследование уровня водородных ионов (pH) крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2463, 'A09.05.043', 'Определение активности креатинкиназы в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2466, 'A09.05.045', 'Определение активности амилазы в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2471, 'A09.05.050', 'Исследование уровня фибриногена в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2482, 'A09.05.060', 'Исследование уровня общего трийодтиронина (Т3) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2485, 'A09.05.063', 'Исследование уровня свободного тироксина (СТ4) сыворотки крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2487, 'A09.05.065', 'Исследование уровня тиреотропного гормона (ТТГ) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2622, 'A09.05.193', 'Исследование уровня тропонинов I, T в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2623, 'A09.05.193.001', 'Экспресс-исследование уровня тропонинов I, T в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2762, 'A09.28.003.001', 'Определение альбумина в моче', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2772, 'A09.28.013', 'Исследование уровня калия в моче', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2773, 'A09.28.014', 'Исследование уровня натрия в моче', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (2787, 'A09.28.027', 'Определение активности альфа-амилазы в моче', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3128, 'A12.05.005', 'Определение основных групп по системе AB0', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3129, 'A12.05.006', 'Определение антигена D системы Резус (резус-фактор)', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3152, 'A12.05.026', 'Исследование уровня кислорода крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3157, 'A12.05.031', 'Определение степени насыщения кислородом гемоглобина', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3169, 'A12.05.039', 'Активированное частичное тромбопластиновое время', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3312, 'A12.10.001', 'Электрокардиография с физической нагрузкой', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3366, 'A12.28.002', 'Исследование функции нефронов по клиренсу креатинина (проба Реберга)', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3376, 'A12.30.004', 'Суточное прикроватное мониторирование жизненных функций и параметров', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3401, 'A13.29.003', 'Клинико-психологическая адаптация', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3413, 'A13.29.008', 'Психотерапия', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3422, 'A13.30.001', 'Обучение самоуходу', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (3955, 'A16.08.003', 'Постановка временной трахеостомы', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5615, 'A17.10.002', 'Электрокардиостимуляция', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4069, 'A16.09.011', 'Искусственная вентиляция легких', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4178, 'A16.10.014', 'Имплантация кардиостимулятора', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4179, 'A16.10.014.001', 'Имплантация однокамерного кардиовертера дефибриллятора', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4200, 'A16.10.024', 'Закрытие дефекта перегородки сердца', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4235, 'A16.12.004', 'Наложение анастомоза на коронарные сосуды', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4236, 'A16.12.004.001', 'Коронарное шунтирование в условиях искусственного кровообращения', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4237, 'A16.12.004.002', 'Коронарное шунтирование на работающем сердце без использования искусственного кровообращения', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4244, 'A16.12.004.009', 'Транслюминальная баллонная ангиопластика и стентирование коронарных артерий', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4248, 'A16.12.008', 'Эндартерэктомия', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4266, 'A16.12.013', 'Аневризмэктомия', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4282, 'A16.12.026', 'Баллонная вазодилятация', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4293, 'A16.12.028', 'Установка стента в сосуд', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (4297, 'A16.12.030', 'Баллонная внутриаортальная контрпульсация', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5612, 'A17.10.001', 'Электроимпульсная терапия при патологии сердца и перикарда', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5616, 'A17.10.002.001', 'Электрокардиостимуляция чреспищеводная', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5738, 'A18.05.015', 'Процедура искусственного кровообращения', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5901, 'A19.10.001', 'Лечебная физкультура при заболеваниях сердца и перикарда', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (5905, 'A19.10.001.004', 'Лечебная физкультура с использованием тренажеров при заболеваниях сердца и перикарда', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6073, 'A20.10.001', 'Оксигенотерапия (гипер- и нормобарическая) при заболеваниях сердца', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6463, 'A23.30.006', 'Определение двигательного режима', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6765, 'A26.06.036', 'Определение антигена (HbsAg) вируса гепатита B (Hepatitis B virus) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6770, 'A26.06.041', 'Определение антител к вирусу гепатита C (Hepatitis C virus) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6777, 'A26.06.048', 'Определение антител классов M, G (IgM, IgG) к вирусу иммунодефицита человека ВИЧ-1 (Human immunodeficiency virus HIV 1) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (6778, 'A26.06.049', 'Определение антител классов M, G (IgM, IgG) к вирусу иммунодефицита человека ВИЧ-2 (Human immunodeficiency virus HIV 2) в крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7358, 'B03.016.004', 'Анализ крови биохимический общетерапевтический', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7030, 'B01.003.001', 'Осмотр (консультация) врачом-анестезиологом-реаниматологом первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7031, 'B01.003.002', 'Осмотр (консультация) врачом-анестезиологом-реаниматологом повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7032, 'B01.003.003', 'Суточное наблюдение врачом-анестезиологом-реаниматологом', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7033, 'B01.003.004', 'Анестезиологическое пособие (включая раннее послеоперационное ведение)', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7045, 'B01.004.001', 'Прием (осмотр, консультация) врача-гастроэнтеролога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7356, 'B03.016.002', 'Общий (клинический) анализ крови', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7076, 'B01.015.001', 'Прием (осмотр, консультация) врача-кардиолога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7077, 'B01.015.002', 'Прием (осмотр, консультация) врача-кардиолога повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7081, 'B01.015.006', 'Ежедневный осмотр врачом-кардиологом с наблюдением и уходом среднего и младшего медицинского персонала в отделении стационара', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7089, 'B01.020.001', 'Прием (осмотр, консультация) врача по лечебной физкультуре', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7093, 'B01.020.005', 'Прием (осмотр, консультация) врача по лечебной физкультуре повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7097, 'B01.023.001', 'Прием (осмотр, консультация) врача-невролога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7098, 'B01.023.002', 'Прием (осмотр, консультация) врача-невролога повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7103, 'B01.025.001', 'Прием (осмотр, консультация) врача-нефролога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7357, 'B03.016.003', 'Общий (клинический) анализ крови развернутый', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7111, 'B01.028.001', 'Прием (осмотр, консультация) врача-оториноларинголога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7114, 'B01.029.001', 'Прием (осмотр, консультация) врача-офтальмолога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7132, 'B01.034.001', 'Прием (осмотр, консультация) врача-психотерапевта первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7133, 'B01.034.002', 'Прием (осмотр, консультация) врача-психотерапевта повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7135, 'B01.035.001', 'Прием (осмотр, консультация) врача-психиатра первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7155, 'B01.037.001', 'Прием (осмотр, консультация) врача-пульмонолога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7169, 'B01.043.001', 'Прием (осмотр, консультация) врача - сердечно-сосудистого хирурга первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7170, 'B01.043.002', 'Прием (осмотр, консультация) врача - сердечно-сосудистого хирурга повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7171, 'B01.043.003', 'Прием (осмотр, консультация) врача по рентгенэндоваскулярным диагностике и лечению первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7172, 'B01.043.004', 'Прием (осмотр, консультация) врача по рентгенэндоваскулярным диагностике и лечению повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7173, 'B01.043.005', 'Ежедневный осмотр врачом - сердечно-сосудистым хирургом с наблюдением и уходом среднего и младшего медицинского персонала в отделении стационара', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7175, 'B01.044.001', 'Осмотр врачом скорой медицинской помощи (врачом-специалистом) при оказании скорой медицинской помощи', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7176, 'B01.044.002', 'Осмотр фельдшером скорой медицинской помощи (специалистом со средним медицинским образованием) при оказании скорой медицинской помощи', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7218, 'B01.053.001', 'Прием (осмотр, консультация) врача-уролога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7241, 'B01.058.001', 'Прием (осмотр, консультация) врача-эндокринолога первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7242, 'B01.058.002', 'Прием (осмотр, консультация) врача-эндокринолога повторный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7247, 'B01.059.001', 'Прием (осмотр, консультация) врача-эндоскописта первичный', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7314, 'B03.005.006', 'Коагулограмма (ориентировочное исследование системы гемостаза)', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7359, 'B03.016.005', 'Анализ крови по оценке нарушений липидного обмена биохимический', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7360, 'B03.016.006', 'Общий (клинический) анализ мочи', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7493, 'B04.015.003', 'Диспансерный прием (осмотр, консультация) врача-кардиолога', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7884, 'A05.10.007.002', 'Дистанционное наблюдение за электрокардиографическими данными', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7954, 'A06.10.006.001', 'Компьютерно-томографическая коронарография', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7969, 'A06.12.059', 'Измерение фракционного резерва коронарного кровотока', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (7970, 'A06.12.060', 'Оптическая когерентная томография коронарных артерий', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (8040, 'A07.10.001.001', 'Сцинтиграфия миокарда с функциональными пробами', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (8045, 'A07.10.003.002', 'Однофотонная эмиссионная компьютерная томография миокарда перфузионная с функциональными пробами', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (9253, 'A16.10.021.001', 'Экстракорпоральная мембранная оксигенация', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (9328, 'A16.12.028.003', 'Стентирование коронарной артерии', 1, null);
INSERT INTO public.exp_view_usl (id, usl_code, name, rel, enable) VALUES (12118, 'A09.20.003', 'Определение фосфорилированной формы протеин-1 связанного инсулиноподобного фактора роста (ПСИФР-1) в цервикальной слизи', 1, null);