create table exp_mkb10
(
    id         integer     not null,
    kodmkb     varchar(10) not null
        constraint exp_mkb10_pk
            primary key,
    name_sh    varchar(100),
    name_mkb10 varchar(250),
    enable     integer
);

alter table exp_mkb10
    owner to exp_user;

create unique index exp_mkb10_id_uindex
    on exp_mkb10 (id);

create unique index exp_mkb10_kodmkb_uindex
    on exp_mkb10 (kodmkb);

INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (1, 'I00', 'Ревматическая лихорадка без упоминания о вовлечении сердца', 'Ревматическая лихорадка без упоминания о вовлечении сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (2, 'I00-I02', 'ОСТРАЯ РЕВМАТИЧЕСКАЯ ЛИХОРАДКА (I00-I02)', 'ОСТРАЯ РЕВМАТИЧЕСКАЯ ЛИХОРАДКА (I00-I02)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (3, 'I00-I99', 'БОЛЕЗНИ СИСТЕМЫ КРОВООБРАЩЕНИЯ (I00-I99)', 'БОЛЕЗНИ СИСТЕМЫ КРОВООБРАЩЕНИЯ (I00-I99)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (4, 'I01', 'Ревматическая лихорадка с вовлечением сердца', 'Ревматическая лихорадка с вовлечением сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (5, 'I01.0', 'Острый ревматический перикардит', 'Острый ревматический перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (6, 'I01.1', 'Острый ревматический эндокардит', 'Острый ревматический эндокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (7, 'I01.2', 'Острый ревматический миокардит', 'Острый ревматический миокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (8, 'I01.8', 'Другие острые ревматические болезни сердца', 'Другие острые ревматические болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (9, 'I01.9', 'Острая ревматическая болезнь сердца неуточненная', 'Острая ревматическая болезнь сердца неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (10, 'I02', 'Ревматическая хорея', 'Ревматическая хорея', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (11, 'I02.0', 'Ревматическая хорея с вовлечением сердца', 'Ревматическая хорея с вовлечением сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (12, 'I02.9', 'Ревматическая хорея без вовлечения сердца', 'Ревматическая хорея без вовлечения сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (13, 'I05', 'Ревматические болезни митрального клапана', 'Ревматические болезни митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (14, 'I05-I09', 'ХРОНИЧЕСКИЕ РЕВМАТИЧЕСКИЕ БОЛЕЗНИ СЕРДЦА (I05-I09)', 'ХРОНИЧЕСКИЕ РЕВМАТИЧЕСКИЕ БОЛЕЗНИ СЕРДЦА (I05-I09)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (15, 'I05.0', 'Митральный стеноз', 'Митральный стеноз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (16, 'I05.1', 'Ревматическая недостаточность митрального клапана', 'Ревматическая недостаточность митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (17, 'I05.2', 'Митральный стеноз с недостаточностью', 'Митральный стеноз с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (18, 'I05.8', 'Другие болезни митрального клапана', 'Другие болезни митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (19, 'I05.9', 'Болезнь митрального клапана неуточненная', 'Болезнь митрального клапана неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (20, 'I06', 'Ревматические болезни аортального клапана', 'Ревматические болезни аортального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (21, 'I06.0', 'Ревматический аортальный стеноз', 'Ревматический аортальный стеноз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (22, 'I06.1', 'Ревматическая недостаточность аортального клапана', 'Ревматическая недостаточность аортального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (23, 'I06.2', 'Ревматический аортальный стеноз с недостаточностью', 'Ревматический аортальный стеноз с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (24, 'I06.8', 'Другие ревматические болезни аортального клапана', 'Другие ревматические болезни аортального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (25, 'I06.9', 'Ревматическая болезнь аортального клапана неуточненная', 'Ревматическая болезнь аортального клапана неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (26, 'I07', 'Ревматические болезни трехстворчатого клапана', 'Ревматические болезни трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (27, 'I07.0', 'Трикуспидальный стеноз', 'Трикуспидальный стеноз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (28, 'I07.1', 'Трикуспидальная недостаточность', 'Трикуспидальная недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (29, 'I07.2', 'Трикуспидальный стеноз с недостаточностью', 'Трикуспидальный стеноз с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (30, 'I07.8', 'Другие болезни трехстворчатого клапана', 'Другие болезни трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (31, 'I07.9', 'Болезнь трехстворчатого клапана неуточненная', 'Болезнь трехстворчатого клапана неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (32, 'I08', 'Поражения нескольких клапанов', 'Поражения нескольких клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (33, 'I08.0', 'Комбинированное поражение митрального и аортального клапанов', 'Комбинированное поражение митрального и аортального клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (34, 'I08.1', 'Комбинированное поражение митрального и трехстворчатого клапанов', 'Комбинированное поражение митрального и трехстворчатого клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (35, 'I08.2', 'Комбинированное поражение аортального и трехстворчатого клапанов', 'Комбинированное поражение аортального и трехстворчатого клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (36, 'I08.3', 'Комбинированное поражение митрального, аортального и трехстворчатого клапанов', 'Комбинированное поражение митрального, аортального и трехстворчатого клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (37, 'I08.8', 'Другие множественные болезни клапанов', 'Другие множественные болезни клапанов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (38, 'I08.9', 'Множественное поражение клапанов неуточненное', 'Множественное поражение клапанов неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (39, 'I09', 'Другие ревматические болезни сердца', 'Другие ревматические болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (40, 'I09.0', 'Ревматический миокардит', 'Ревматический миокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (41, 'I09.1', 'Ревматические болезни эндокарда, клапан не уточнен', 'Ревматические болезни эндокарда, клапан не уточнен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (42, 'I09.2', 'Хронический ревматический перикардит', 'Хронический ревматический перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (43, 'I09.8', 'Другие уточненные ревматические болезни сердца', 'Другие уточненные ревматические болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (44, 'I09.9', 'Ревматические болезни сердца неуточненные', 'Ревматические болезни сердца неуточненные', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (45, 'I10', 'Эссенциальная [первичная] гипертензия', 'Эссенциальная [первичная] гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (46, 'I10-I15', 'БОЛЕЗНИ, ХАРАКТЕРИЗУЮЩИЕСЯ ПОВЫШЕННЫМ КРОВЯНЫМ ДАВЛЕНИЕМ (I10-I15)', 'БОЛЕЗНИ, ХАРАКТЕРИЗУЮЩИЕСЯ ПОВЫШЕННЫМ КРОВЯНЫМ ДАВЛЕНИЕМ (I10-I15)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (47, 'I11', 'Гипертензивная болезнь сердца [гипертоническая болезнь с преимущественным поражением сердца]', 'Гипертензивная болезнь сердца [гипертоническая болезнь с преимущественным поражением сердца]', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (48, 'I11.0', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца с (застойной) сердечно', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца с (застойной) сердечной недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (49, 'I11.9', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца без (застойной) сердеч', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца без (застойной) сердечной недостаточности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (50, 'I12', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (51, 'I12.0', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек с почечной недостаточно', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек с почечной недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (52, 'I12.9', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек без почечной недостаточ', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением почек без почечной недостаточности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (53, 'I13', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (54, 'I13.0', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с (застойной) ', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с (застойной) сердечной недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (55, 'I13.1', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с почечной нед', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с почечной недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (56, 'I13.2', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с (застойной) ', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек с (застойной) сердечной недостаточностью и почечной недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (57, 'I13.9', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек неуточненная', 'Гипертензивная [гипертоническая] болезнь с преимущественным поражением сердца и почек неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (58, 'I15', 'Вторичная гипертензия', 'Вторичная гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (59, 'I15.0', 'Реноваскулярная гипертензия', 'Реноваскулярная гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (60, 'I15.1', 'Гипертензия вторичная по отношению к другим поражениям почек', 'Гипертензия вторичная по отношению к другим поражениям почек', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (61, 'I15.2', 'Гипертензия вторичная по отношению к эндокринным нарушениям', 'Гипертензия вторичная по отношению к эндокринным нарушениям', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (62, 'I15.8', 'Другая вторичная гипертензия', 'Другая вторичная гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (63, 'I15.9', 'Вторичная гипертензия неуточненная', 'Вторичная гипертензия неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (64, 'I20', 'Стенокардия [грудная жаба]', 'Стенокардия [грудная жаба]', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (65, 'I20-I25', 'ИШЕМИЧЕСКАЯ БОЛЕЗНЬ СЕРДЦА (I20-I25)', 'ИШЕМИЧЕСКАЯ БОЛЕЗНЬ СЕРДЦА (I20-I25)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (67, 'I20.1', 'Стенокардия с документально подтвержденным спазмом', 'Стенокардия с документально подтвержденным спазмом', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (68, 'I20.8', 'Другие формы стенокардии', 'Другие формы стенокардии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (69, 'I20.9', 'Стенокардия неуточненная', 'Стенокардия неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (96, 'I25', 'Хроническая ишемическая болезнь сердца', 'Хроническая ишемическая болезнь сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (97, 'I25.0', 'Атеросклеротическая сердечно-сосудистая болезнь, так описанная', 'Атеросклеротическая сердечно-сосудистая болезнь, так описанная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (98, 'I25.1', 'Атеросклеротическая болезнь сердца', 'Атеросклеротическая болезнь сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (99, 'I25.2', 'Перенесенный в прошлом инфаркт миокарда', 'Перенесенный в прошлом инфаркт миокарда', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (100, 'I25.3', 'Аневризма сердца', 'Аневризма сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (101, 'I25.4', 'Аневризма и расслоение коронарной артерии', 'Аневризма и расслоение коронарной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (102, 'I25.5', 'Ишемическая кардиомиопатия', 'Ишемическая кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (103, 'I25.6', 'Бессимптомная ишемия миокарда', 'Бессимптомная ишемия миокарда', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (104, 'I25.8', 'Другие формы хронической ишемической болезни сердца', 'Другие формы хронической ишемической болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (105, 'I25.9', 'Хроническая ишемическая болезнь сердца неуточненная', 'Хроническая ишемическая болезнь сердца неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (106, 'I26', 'Легочная эмболия', 'Легочная эмболия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (107, 'I26-I28', 'ЛЕГОЧНОЕ СЕРДЦЕ И НАРУШЕНИЯ ЛЕГОЧНОГО КРОВООБРАЩЕНИЯ (I26-I28)', 'ЛЕГОЧНОЕ СЕРДЦЕ И НАРУШЕНИЯ ЛЕГОЧНОГО КРОВООБРАЩЕНИЯ (I26-I28)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (108, 'I26.0', 'Легочная эмболия с упоминанием об остром легочном сердце', 'Легочная эмболия с упоминанием об остром легочном сердце', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (109, 'I26.9', 'Легочная эмболия без упоминания об остром легочном сердце', 'Легочная эмболия без упоминания об остром легочном сердце', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (110, 'I27', 'Другие формы легочно-сердечной недостаточности', 'Другие формы легочно-сердечной недостаточности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (111, 'I27.0', 'Первичная легочная гипертензия', 'Первичная легочная гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (112, 'I27.1', 'Кифосколиотическая болезнь сердца', 'Кифосколиотическая болезнь сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (113, 'I27.2', 'Другая вторичная легочная гипертензия', 'Другая вторичная легочная гипертензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (114, 'I27.8', 'Другие уточненные формы легочно-сердечной недостаточности', 'Другие уточненные формы легочно-сердечной недостаточности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (115, 'I27.9', 'Легочно-сердечная недостаточность неуточненная', 'Легочно-сердечная недостаточность неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (116, 'I28', 'Другие болезни легочных сосудов', 'Другие болезни легочных сосудов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (117, 'I28.0', 'Артериовенозный свищ легочных сосудов', 'Артериовенозный свищ легочных сосудов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (118, 'I28.1', 'Аневризма легочной артерии', 'Аневризма легочной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (119, 'I28.8', 'Другие уточненные болезни легочных сосудов', 'Другие уточненные болезни легочных сосудов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (120, 'I28.9', 'Болезнь легочных сосудов неуточненная', 'Болезнь легочных сосудов неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (121, 'I30', 'Острый перикардит', 'Острый перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (122, 'I30-I52', 'ДРУГИЕ БОЛЕЗНИ СЕРДЦА (I30-I52)', 'ДРУГИЕ БОЛЕЗНИ СЕРДЦА (I30-I52)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (123, 'I30.0', 'Острый неспецифический идиопатический перикардит', 'Острый неспецифический идиопатический перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (124, 'I30.1', 'Инфекционный перикардит', 'Инфекционный перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (125, 'I30.8', 'Другие формы острого перикардита', 'Другие формы острого перикардита', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (126, 'I30.9', 'Острый перикардит неуточненный', 'Острый перикардит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (127, 'I31', 'Другие болезни перикарда', 'Другие болезни перикарда', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (128, 'I31.0', 'Хронический адгезивный перикардит', 'Хронический адгезивный перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (129, 'I31.1', 'Хронический констриктивный перикардит', 'Хронический констриктивный перикардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (130, 'I31.2', 'Гемоперикард, не классифицированный в других рубриках', 'Гемоперикард, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (131, 'I31.3', 'Перикардиальный выпот (невоспалительный)', 'Перикардиальный выпот (невоспалительный)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (132, 'I31.8', 'Другие уточненные болезни перикарда', 'Другие уточненные болезни перикарда', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (133, 'I31.9', 'Болезни перикарда неуточненные', 'Болезни перикарда неуточненные', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (134, 'I32', 'Перикардит при болезнях, классифицированных в других рубриках', 'Перикардит при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (135, 'I32.0', 'Перикардит при бактериальных болезнях, классифицированных в других рубриках', 'Перикардит при бактериальных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (136, 'I32.1', 'Перикардит при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', 'Перикардит при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (137, 'I32.8', 'Перикардит при других болезнях, классифицированных в других рубриках', 'Перикардит при других болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (138, 'I33', 'Острый и подострый эндокардит', 'Острый и подострый эндокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (139, 'I33.0', 'Острый и подострый инфекционный эндокардит', 'Острый и подострый инфекционный эндокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (140, 'I33.9', 'Острый эндокардит неуточненный', 'Острый эндокардит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (141, 'I34', 'Неревматические поражения митрального клапана', 'Неревматические поражения митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (142, 'I34.0', 'Митральная (клапанная) недостаточность', 'Митральная (клапанная) недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (143, 'I34.1', 'Пролапс [пролабирование] митрального клапана', 'Пролапс [пролабирование] митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (144, 'I34.2', 'Неревматический стеноз митрального клапана', 'Неревматический стеноз митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (145, 'I34.8', 'Другие неревматические поражения митрального клапана', 'Другие неревматические поражения митрального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (146, 'I34.9', 'Неревматическое поражение митрального клапана неуточненное', 'Неревматическое поражение митрального клапана неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (147, 'I35', 'Неревматические поражения аортального клапана', 'Неревматические поражения аортального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (148, 'I35.0', 'Аортальный (клапанный) стеноз', 'Аортальный (клапанный) стеноз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (149, 'I35.1', 'Аортальная (клапанная) недостаточность', 'Аортальная (клапанная) недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (150, 'I35.2', 'Аортальный (клапанный) стеноз с недостаточностью', 'Аортальный (клапанный) стеноз с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (151, 'I35.8', 'Другие поражения аортального клапана', 'Другие поражения аортального клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (152, 'I35.9', 'Поражение аортального клапана неуточненное', 'Поражение аортального клапана неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (153, 'I36', 'Неревматические поражения трехстворчатого клапана', 'Неревматические поражения трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (154, 'I36.0', 'Неревматический стеноз трехстворчатого клапана', 'Неревматический стеноз трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (155, 'I36.1', 'Неревматическая недостаточность трехстворчатого клапана', 'Неревматическая недостаточность трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (156, 'I36.2', 'Неревматический стеноз трехстворчатого клапана с недостаточностью', 'Неревматический стеноз трехстворчатого клапана с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (157, 'I36.8', 'Другие неревматические поражения трехстворчатого клапана', 'Другие неревматические поражения трехстворчатого клапана', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (158, 'I36.9', 'Неревматическое поражение трехстворчатого клапана неуточненное', 'Неревматическое поражение трехстворчатого клапана неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (159, 'I37', 'Поражения клапана легочной артерии', 'Поражения клапана легочной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (160, 'I37.0', 'Стеноз клапана легочной артерии', 'Стеноз клапана легочной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (161, 'I37.1', 'Недостаточность клапана легочной артерии', 'Недостаточность клапана легочной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (162, 'I37.2', 'Стеноз клапана легочной артерии с недостаточностью', 'Стеноз клапана легочной артерии с недостаточностью', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (163, 'I37.8', 'Другие поражения клапана легочной артерии', 'Другие поражения клапана легочной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (164, 'I37.9', 'Поражение клапана легочной артерии неуточненное', 'Поражение клапана легочной артерии неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (165, 'I38', 'Эндокардит, клапан не уточнен', 'Эндокардит, клапан не уточнен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (166, 'I39', 'Эндокардит и поражения клапанов сердца при болезнях, классифицированных в других рубриках', 'Эндокардит и поражения клапанов сердца при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (167, 'I39.0', 'Поражения митрального клапана при болезнях, классифицированных в других рубриках', 'Поражения митрального клапана при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (168, 'I39.1', 'Поражения аортального клапана при болезнях, классифицированных в других рубриках', 'Поражения аортального клапана при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (169, 'I39.2', 'Поражения трехстворчатого клапана при болезнях, классифицированных в других рубриках', 'Поражения трехстворчатого клапана при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (170, 'I39.3', 'Поражения клапана легочной артерии при болезнях, классифицированных в других рубриках', 'Поражения клапана легочной артерии при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (171, 'I39.4', 'Множественные поражения клапанов при болезнях, классифицированных в других рубриках', 'Множественные поражения клапанов при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (172, 'I39.8', 'Эндокардит, клапан не уточнен, при болезнях, классифицированных в других рубриках', 'Эндокардит, клапан не уточнен, при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (173, 'I40', 'Острый миокардит', 'Острый миокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (174, 'I40.0', 'Инфекционный миокардит', 'Инфекционный миокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (175, 'I40.1', 'Изолированный миокардит', 'Изолированный миокардит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (176, 'I40.8', 'Другие виды острого миокардита', 'Другие виды острого миокардита', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (177, 'I40.9', 'Острый миокардит неуточненный', 'Острый миокардит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (214, 'I45.5', 'Другая уточненная блокада сердца', 'Другая уточненная блокада сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (178, 'I41', 'Миокардит при болезнях, классифицированных в других рубриках', 'Миокардит при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (179, 'I41.0', 'Миокардит при бактериальных болезнях, классифицированных в других рубриках', 'Миокардит при бактериальных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (180, 'I41.1', 'Миокардит при вирусных болезнях, классифицированных в других рубриках', 'Миокардит при вирусных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (181, 'I41.2', 'Миокардит при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', 'Миокардит при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (182, 'I41.8', 'Миокардит при других болезнях, классифицированных в других рубриках', 'Миокардит при других болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (183, 'I42', 'Кардиомиопатия', 'Кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (184, 'I42.0', 'Дилатационная кардиомиопатия', 'Дилатационная кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (185, 'I42.1', 'Обструктивная гипертрофическая кардиомиопатия', 'Обструктивная гипертрофическая кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (186, 'I42.2', 'Другая гипертрофическая кардиомиопатия', 'Другая гипертрофическая кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (187, 'I42.3', 'Эндомиокардиальная (эозинофильная) болезнь', 'Эндомиокардиальная (эозинофильная) болезнь', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (188, 'I42.4', 'Эндокардиальный фиброэластоз', 'Эндокардиальный фиброэластоз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (189, 'I42.5', 'Другая рестриктивная кардиомиопатия', 'Другая рестриктивная кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (190, 'I42.6', 'Алкогольная кардиомиопатия', 'Алкогольная кардиомиопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (191, 'I42.7', 'Кардиомиопатия, обусловленная воздействием лекарственных средств и других внешних факторов', 'Кардиомиопатия, обусловленная воздействием лекарственных средств и других внешних факторов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (192, 'I42.8', 'Другие кардиомиопатии', 'Другие кардиомиопатии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (193, 'I42.9', 'Кардиомиопатия неуточненная', 'Кардиомиопатия неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (194, 'I43', 'Кардиомиопатия при болезнях, классифицированных в других рубриках', 'Кардиомиопатия при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (195, 'I43.0', 'Кардиомиопатия при инфекционных и паразитарных болезнях, классифицированных в других рубриках', 'Кардиомиопатия при инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (196, 'I43.1', 'Кардиомиопатия при метаболических нарушениях', 'Кардиомиопатия при метаболических нарушениях', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (197, 'I43.2', 'Кардиомиопатия при расстройствах питания', 'Кардиомиопатия при расстройствах питания', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (198, 'I43.8', 'Кардиомиопатия при других болезнях, классифицированных в других рубриках', 'Кардиомиопатия при других болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (199, 'I44', 'Предсердно-желудочковая [атриовентрикулярная] блокада и блокада левой ножки пучка Гиса', 'Предсердно-желудочковая [атриовентрикулярная] блокада и блокада левой ножки пучка Гиса', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (200, 'I44.0', 'Предсердно-желудочковая блокада первой степени', 'Предсердно-желудочковая блокада первой степени', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (201, 'I44.1', 'Предсердно-желудочковая блокада второй степени', 'Предсердно-желудочковая блокада второй степени', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (202, 'I44.2', 'Предсердно-желудочковая блокада полная', 'Предсердно-желудочковая блокада полная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (203, 'I44.3', 'Другая и неуточненная предсердно-желудочковая блокада', 'Другая и неуточненная предсердно-желудочковая блокада', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (204, 'I44.4', 'Блокада передней ветви левой ножки пучка', 'Блокада передней ветви левой ножки пучка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (205, 'I44.5', 'Блокада задней ветви левой ножки пучка', 'Блокада задней ветви левой ножки пучка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (206, 'I44.6', 'Другие и неуточненные блокады пучка', 'Другие и неуточненные блокады пучка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (207, 'I44.7', 'Блокада левой ножки пучка неуточненная', 'Блокада левой ножки пучка неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (208, 'I45', 'Другие нарушения проводимости', 'Другие нарушения проводимости', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (209, 'I45.0', 'Блокада правой ножки пучка', 'Блокада правой ножки пучка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (210, 'I45.1', 'Другая и неуточненная блокада правой ножки пучка', 'Другая и неуточненная блокада правой ножки пучка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (211, 'I45.2', 'Двухпучковая блокада', 'Двухпучковая блокада', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (212, 'I45.3', 'Трехпучковая блокада', 'Трехпучковая блокада', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (213, 'I45.4', 'Неспецифическая внутрижелудочковая блокада', 'Неспецифическая внутрижелудочковая блокада', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (215, 'I45.6', 'Синдром преждевременного возбуждения', 'Синдром преждевременного возбуждения', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (216, 'I45.8', 'Другие уточненные нарушения проводимости', 'Другие уточненные нарушения проводимости', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (217, 'I45.9', 'Нарушение проводимости неуточненное', 'Нарушение проводимости неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (218, 'I46', 'Остановка сердца', 'Остановка сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (219, 'I46.0', 'Остановка сердца с успешным восстановлением сердечной деятельности', 'Остановка сердца с успешным восстановлением сердечной деятельности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (220, 'I46.1', 'Внезапная сердечная смерть, так описанная', 'Внезапная сердечная смерть, так описанная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (221, 'I46.9', 'Остановка сердца неуточненная', 'Остановка сердца неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (222, 'I47', 'Пароксизмальная тахикардия', 'Пароксизмальная тахикардия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (223, 'I47.0', 'Возвратная желудочковая аритмия', 'Возвратная желудочковая аритмия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (224, 'I47.1', 'Наджелудочковая тахикардия', 'Наджелудочковая тахикардия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (225, 'I47.2', 'Желудочковая тахикардия', 'Желудочковая тахикардия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (226, 'I47.9', 'Пароксизмальная тахикардия неуточненная', 'Пароксизмальная тахикардия неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (227, 'I48', 'Фибрилляция и трепетание предсердий', 'Фибрилляция и трепетание предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (228, 'I48.0', 'Пароксизмальная форма фибрилляции предсердий', 'Пароксизмальная форма фибрилляции предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (229, 'I48.1', 'Постоянная форма фибрилляции предсердий', 'Постоянная форма фибрилляции предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (230, 'I48.2', 'Хроническая форма фибрилляции предсердий', 'Хроническая форма фибрилляции предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (231, 'I48.3', 'Типичная форма трепетания предсердий', 'Типичная форма трепетания предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (232, 'I48.4', 'Атипичная форма трепетания предсердий', 'Атипичная форма трепетания предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (233, 'I48.9', 'Фибрилляция и трепетание предсердий неуточненное', 'Фибрилляция и трепетание предсердий неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (234, 'I49', 'Другие нарушения сердечного ритма', 'Другие нарушения сердечного ритма', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (235, 'I49.0', 'Фибрилляция и трепетание желудочков', 'Фибрилляция и трепетание желудочков', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (236, 'I49.1', 'Преждевременная деполяризация предсердий', 'Преждевременная деполяризация предсердий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (237, 'I49.2', 'Преждевременная деполяризация, исходящая из соединения', 'Преждевременная деполяризация, исходящая из соединения', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (238, 'I49.3', 'Преждевременная деполяризация желудочков', 'Преждевременная деполяризация желудочков', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (239, 'I49.4', 'Другая и неуточненная преждевременная деполяризация', 'Другая и неуточненная преждевременная деполяризация', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (240, 'I49.5', 'Синдром слабости синусового узла', 'Синдром слабости синусового узла', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (241, 'I49.8', 'Другие уточненные нарушения сердечного ритма', 'Другие уточненные нарушения сердечного ритма', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (242, 'I49.9', 'Нарушение сердечного ритма неуточненное', 'Нарушение сердечного ритма неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (243, 'I50', 'Сердечная недостаточность', 'Сердечная недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (244, 'I50.0', 'Застойная сердечная недостаточность', 'Застойная сердечная недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (245, 'I50.1', 'Левожелудочковая недостаточность', 'Левожелудочковая недостаточность', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (246, 'I50.9', 'Сердечная недостаточность неуточненная', 'Сердечная недостаточность неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (247, 'I51', 'Осложнения и неточно обозначенные болезни сердца', 'Осложнения и неточно обозначенные болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (248, 'I51.0', 'Дефект перегородки сердца приобретенный', 'Дефект перегородки сердца приобретенный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (249, 'I51.1', 'Разрыв сухожилий хорды, не классифицированный в других рубриках', 'Разрыв сухожилий хорды, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (250, 'I51.2', 'Разрыв сосочковой мышцы, не классифицированный в других рубриках', 'Разрыв сосочковой мышцы, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (251, 'I51.3', 'Внутрисердечный тромбоз, не классифицированный в других рубриках', 'Внутрисердечный тромбоз, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (252, 'I51.4', 'Миокардит неуточненный', 'Миокардит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (253, 'I51.5', 'Дегенерация миокарда', 'Дегенерация миокарда', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (254, 'I51.6', 'Сердечно-сосудистая болезнь неуточненная', 'Сердечно-сосудистая болезнь неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (255, 'I51.7', 'Кардиомегалия', 'Кардиомегалия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (256, 'I51.8', 'Другие неточно обозначенные болезни сердца', 'Другие неточно обозначенные болезни сердца', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (257, 'I51.9', 'Болезнь сердца неуточненная', 'Болезнь сердца неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (258, 'I52', 'Другие поражения сердца при болезнях, классифицированных в других рубриках', 'Другие поражения сердца при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (259, 'I52.0', 'Другие поражения сердца при бактериальных болезнях, классифицированных в других рубриках', 'Другие поражения сердца при бактериальных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (260, 'I52.1', 'Другие поражения сердца при других инфекционных и паразитарных болезнях, классифицированных в других', 'Другие поражения сердца при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (261, 'I52.8', 'Другие поражения сердца при других болезнях, классифицированных в других рубриках', 'Другие поражения сердца при других болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (262, 'I60', 'Субарахноидальное кровоизлияние', 'Субарахноидальное кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (263, 'I60-I69', 'ЦЕРЕБРОВАСКУЛЯРНЫЕ БОЛЕЗНИ (I60-I69)', 'ЦЕРЕБРОВАСКУЛЯРНЫЕ БОЛЕЗНИ (I60-I69)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (264, 'I60.0', 'Субарахноидальное кровоизлияние из каротидного синуса и бифуркации', 'Субарахноидальное кровоизлияние из каротидного синуса и бифуркации', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (265, 'I60.1', 'Субарахноидальное кровоизлияние из средней мозговой артерии', 'Субарахноидальное кровоизлияние из средней мозговой артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (266, 'I60.2', 'Субарахноидальное кровоизлияние из передней соединительной артерии', 'Субарахноидальное кровоизлияние из передней соединительной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (267, 'I60.3', 'Субарахноидальное кровоизлияние из задней соединительной артерии', 'Субарахноидальное кровоизлияние из задней соединительной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (268, 'I60.4', 'Субарахноидальное кровоизлияние из базилярной артерии', 'Субарахноидальное кровоизлияние из базилярной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (269, 'I60.5', 'Субарахноидальное кровоизлияние из позвоночной артерии', 'Субарахноидальное кровоизлияние из позвоночной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (270, 'I60.6', 'Субарахноидальное кровоизлияние из других внутричерепных артерий', 'Субарахноидальное кровоизлияние из других внутричерепных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (271, 'I60.7', 'Субарахноидальное кровоизлияние из внутричерепной артерии неуточненной', 'Субарахноидальное кровоизлияние из внутричерепной артерии неуточненной', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (272, 'I60.8', 'Другое субарахноидальное кровоизлияние', 'Другое субарахноидальное кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (273, 'I60.9', 'Субарахноидальное кровоизлияние неуточненное', 'Субарахноидальное кровоизлияние неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (274, 'I61', 'Внутримозговое кровоизлияние', 'Внутримозговое кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (275, 'I61.0', 'Внутримозговое кровоизлияние в полушарие субкортикальное', 'Внутримозговое кровоизлияние в полушарие субкортикальное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (276, 'I61.1', 'Внутримозговое кровоизлияние в полушарие кортикальное', 'Внутримозговое кровоизлияние в полушарие кортикальное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (277, 'I61.2', 'Внутримозговое кровоизлияние в полушарие неуточненное', 'Внутримозговое кровоизлияние в полушарие неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (278, 'I61.3', 'Внутримозговое кровоизлияние в ствол мозга', 'Внутримозговое кровоизлияние в ствол мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (279, 'I61.4', 'Внутримозговое кровоизлияние в мозжечок', 'Внутримозговое кровоизлияние в мозжечок', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (280, 'I61.5', 'Внутримозговое кровоизлияние внутрижелудочковое', 'Внутримозговое кровоизлияние внутрижелудочковое', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (281, 'I61.6', 'Внутримозговое кровоизлияние множественной локализации', 'Внутримозговое кровоизлияние множественной локализации', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (282, 'I61.8', 'Другое внутримозговое кровоизлияние', 'Другое внутримозговое кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (283, 'I61.9', 'Внутримозговое кровоизлияние неуточненное', 'Внутримозговое кровоизлияние неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (284, 'I62', 'Другое нетравматическое внутричерепное кровоизлияние', 'Другое нетравматическое внутричерепное кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (285, 'I62.0', 'Нетравматическое субдуральное кровоизлияние', 'Нетравматическое субдуральное кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (286, 'I62.1', 'Нетравматическое экстрадуральное кровоизлияние', 'Нетравматическое экстрадуральное кровоизлияние', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (287, 'I62.9', 'Внутричерепное кровоизлияние (нетравматическое) неуточненное', 'Внутричерепное кровоизлияние (нетравматическое) неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (288, 'I63', 'Инфаркт мозга', 'Инфаркт мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (289, 'I63.0', 'Инфаркт мозга, вызванный тромбозом прецеребральных артерий', 'Инфаркт мозга, вызванный тромбозом прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (290, 'I63.1', 'Инфаркт мозга, вызванный эмболией прецеребральных артерий', 'Инфаркт мозга, вызванный эмболией прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (291, 'I63.2', 'Инфаркт мозга, вызванный неуточненной закупоркой или стенозом прецеребральных артерий', 'Инфаркт мозга, вызванный неуточненной закупоркой или стенозом прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (292, 'I63.3', 'Инфаркт мозга, вызванный тромбозом мозговых артерий', 'Инфаркт мозга, вызванный тромбозом мозговых артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (293, 'I63.4', 'Инфаркт мозга, вызванный эмболией мозговых артерий', 'Инфаркт мозга, вызванный эмболией мозговых артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (294, 'I63.5', 'Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий', 'Инфаркт мозга, вызванный неуточненной закупоркой или стенозом мозговых артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (295, 'I63.6', 'Инфаркт мозга, вызванный тромбозом вен мозга, непиогенный', 'Инфаркт мозга, вызванный тромбозом вен мозга, непиогенный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (296, 'I63.8', 'Другой инфаркт мозга', 'Другой инфаркт мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (297, 'I63.9', 'Инфаркт мозга неуточненный', 'Инфаркт мозга неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (298, 'I64', 'Инсульт, не уточненный как кровоизлияние или инфаркт', 'Инсульт, не уточненный как кровоизлияние или инфаркт', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (299, 'I65', 'Закупорка и стеноз прецеребральных артерий, не приводящие к инфаркту мозга', 'Закупорка и стеноз прецеребральных артерий, не приводящие к инфаркту мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (300, 'I65.0', 'Закупорка и стеноз позвоночной артерии', 'Закупорка и стеноз позвоночной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (301, 'I65.1', 'Закупорка и стеноз базилярной артерии', 'Закупорка и стеноз базилярной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (302, 'I65.2', 'Закупорка и стеноз сонной артерии', 'Закупорка и стеноз сонной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (303, 'I65.3', 'Закупорка и стеноз множественных и двусторонних прецеребральных артерий', 'Закупорка и стеноз множественных и двусторонних прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (304, 'I65.8', 'Закупорка и стеноз других прецеребральных артерий', 'Закупорка и стеноз других прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (305, 'I65.9', 'Закупорка и стеноз неуточненной прецеребральной артерии', 'Закупорка и стеноз неуточненной прецеребральной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (306, 'I66', 'Закупорка и стеноз церебральных артерий, не приводящие к инфаркту мозга', 'Закупорка и стеноз церебральных артерий, не приводящие к инфаркту мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (307, 'I66.0', 'Закупорка и стеноз средней мозговой артерии', 'Закупорка и стеноз средней мозговой артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (308, 'I66.1', 'Закупорка и стеноз передней мозговой артерии', 'Закупорка и стеноз передней мозговой артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (309, 'I66.2', 'Закупорка и стеноз задней мозговой артерии', 'Закупорка и стеноз задней мозговой артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (310, 'I66.3', 'Закупорка и стеноз мозжечковых артерий', 'Закупорка и стеноз мозжечковых артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (311, 'I66.4', 'Закупорка и стеноз множественных и двусторонних артерий мозга', 'Закупорка и стеноз множественных и двусторонних артерий мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (312, 'I66.8', 'Закупорка и стеноз другой артерии мозга', 'Закупорка и стеноз другой артерии мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (313, 'I66.9', 'Закупорка и стеноз артерии мозга неуточненной', 'Закупорка и стеноз артерии мозга неуточненной', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (314, 'I67', 'Другие цереброваскулярные болезни', 'Другие цереброваскулярные болезни', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (315, 'I67.0', 'Расслоение мозговых артерий без разрыва', 'Расслоение мозговых артерий без разрыва', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (316, 'I67.1', 'Аневризма мозга без разрыва', 'Аневризма мозга без разрыва', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (317, 'I67.2', 'Церебральный атеросклероз', 'Церебральный атеросклероз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (318, 'I67.3', 'Прогрессирующая сосудистая лейкоэнцефалопатия', 'Прогрессирующая сосудистая лейкоэнцефалопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (319, 'I67.4', 'Гипертензивная энцефалопатия', 'Гипертензивная энцефалопатия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (320, 'I67.5', 'Болезнь Мойамойа', 'Болезнь Мойамойа', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (321, 'I67.6', 'Негнойный тромбоз внутричерепной венозной системы', 'Негнойный тромбоз внутричерепной венозной системы', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (322, 'I67.7', 'Церебральный артериит, не классифицированный в других рубриках', 'Церебральный артериит, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (323, 'I67.8', 'Другие уточненные поражения сосудов мозга', 'Другие уточненные поражения сосудов мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (324, 'I67.9', 'Цереброваскулярная болезнь неуточненная', 'Цереброваскулярная болезнь неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (325, 'I68', 'Поражения сосудов мозга при болезнях, классифицированных в других рубриках', 'Поражения сосудов мозга при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (326, 'I68.0', 'Церебральная амилоидная ангиопатия (E85.-+)', 'Церебральная амилоидная ангиопатия (E85.-+)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (327, 'I68.1', 'Церебральный артериит при инфекционных и паразитарных болезнях, классифицированных в других рубриках', 'Церебральный артериит при инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (328, 'I68.2', 'Церебральный артериит при других болезнях, классифицированных в других рубриках', 'Церебральный артериит при других болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (329, 'I68.8', 'Другие поражения сосудов мозга при болезнях, классифицированных в других рубриках', 'Другие поражения сосудов мозга при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (330, 'I69', 'Последствия цереброваскулярных болезней', 'Последствия цереброваскулярных болезней', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (331, 'I69.0', 'Последствия субарахноидального кровоизлияния', 'Последствия субарахноидального кровоизлияния', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (332, 'I69.1', 'Последствия внутричерепного кровоизлияния', 'Последствия внутричерепного кровоизлияния', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (333, 'I69.2', 'Последствия другого нетравматического внутричерепного кровоизлияния', 'Последствия другого нетравматического внутричерепного кровоизлияния', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (334, 'I69.3', 'Последствия инфаркта мозга', 'Последствия инфаркта мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (335, 'I69.4', 'Последствия инсульта, не уточненные как кровоизлияние или инфаркт мозга', 'Последствия инсульта, не уточненные как кровоизлияние или инфаркт мозга', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (336, 'I69.8', 'Последствия других и неуточненных цереброваскулярных болезней', 'Последствия других и неуточненных цереброваскулярных болезней', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (337, 'I70', 'Атеросклероз', 'Атеросклероз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (338, 'I70-I79', 'БОЛЕЗНЬ АРТЕРИЙ, АРТЕРИОЛ И КАПИЛЛЯРОВ (I70-I79)', 'БОЛЕЗНЬ АРТЕРИЙ, АРТЕРИОЛ И КАПИЛЛЯРОВ (I70-I79)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (339, 'I70.0', 'Атеросклероз аорты', 'Атеросклероз аорты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (340, 'I70.1', 'Атеросклероз почечной артерии', 'Атеросклероз почечной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (341, 'I70.2', 'Атеросклероз артерий конечностей', 'Атеросклероз артерий конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (342, 'I70.8', 'Атеросклероз других артерий', 'Атеросклероз других артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (343, 'I70.9', 'Генерализованный и неуточненный атеросклероз', 'Генерализованный и неуточненный атеросклероз', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (344, 'I71', 'Аневризма и расслоение аорты', 'Аневризма и расслоение аорты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (345, 'I71.0', 'Расслоение аорты (любой части)', 'Расслоение аорты (любой части)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (346, 'I71.1', 'Аневризма грудной части аорты разорванная', 'Аневризма грудной части аорты разорванная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (347, 'I71.2', 'Аневризма грудной части аорты без упоминания о разрыве', 'Аневризма грудной части аорты без упоминания о разрыве', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (348, 'I71.3', 'Аневризма брюшной аорты разорванная', 'Аневризма брюшной аорты разорванная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (349, 'I71.4', 'Аневризма брюшной аорты без упоминания о разрыве', 'Аневризма брюшной аорты без упоминания о разрыве', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (350, 'I71.5', 'Аневризма грудной и брюшной аорты разорванная', 'Аневризма грудной и брюшной аорты разорванная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (351, 'I71.6', 'Аневризма грудной и брюшной аорты без упоминания о разрыве', 'Аневризма грудной и брюшной аорты без упоминания о разрыве', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (352, 'I71.8', 'Аневризма аорты неуточненной локализации разорванная', 'Аневризма аорты неуточненной локализации разорванная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (353, 'I71.9', 'Аневризма аорты неуточненной локализации без упоминания о разрыве', 'Аневризма аорты неуточненной локализации без упоминания о разрыве', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (354, 'I72', 'Другая аневризма и расслоение', 'Другая аневризма и расслоение', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (355, 'I72.0', 'Аневризма и расслоение сонной артерии', 'Аневризма и расслоение сонной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (356, 'I72.1', 'Аневризма и расслоение артерии верхней конечности', 'Аневризма и расслоение артерии верхней конечности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (357, 'I72.2', 'Аневризма и расслоение почечной артерии', 'Аневризма и расслоение почечной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (358, 'I72.3', 'Аневризма и расслоение подвздошной артерии', 'Аневризма и расслоение подвздошной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (359, 'I72.4', 'Аневризма и расслоение артерии нижней конечности', 'Аневризма и расслоение артерии нижней конечности', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (360, 'I72.5', 'Аневризма и расслоение других прецеребральных артерий', 'Аневризма и расслоение других прецеребральных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (361, 'I72.6', 'Аневризма и расслоение позвоночной артерии', 'Аневризма и расслоение позвоночной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (362, 'I72.8', 'Аневризма и расслоение других уточненных артерий', 'Аневризма и расслоение других уточненных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (363, 'I72.9', 'Аневризма и расслоение неуточненной локализации', 'Аневризма и расслоение неуточненной локализации', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (364, 'I73', 'Другие болезни периферических сосудов', 'Другие болезни периферических сосудов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (365, 'I73.0', 'Синдром Рейно', 'Синдром Рейно', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (366, 'I73.1', 'Облитерирующий тромбангиит [болезнь Бюргера]', 'Облитерирующий тромбангиит [болезнь Бюргера]', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (367, 'I73.8', 'Другие уточненные болезни периферических сосудов', 'Другие уточненные болезни периферических сосудов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (368, 'I73.9', 'Болезнь периферических сосудов неуточненная', 'Болезнь периферических сосудов неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (369, 'I74', 'Эмболия и тромбоз артерий', 'Эмболия и тромбоз артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (370, 'I74.0', 'Эмболия и тромбоз брюшной аорты', 'Эмболия и тромбоз брюшной аорты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (371, 'I74.1', 'Эмболия и тромбоз других и неуточненных отделов аорты', 'Эмболия и тромбоз других и неуточненных отделов аорты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (372, 'I74.2', 'Эмболия и тромбоз артерий верхних конечностей', 'Эмболия и тромбоз артерий верхних конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (373, 'I74.3', 'Эмболия и тромбоз артерий нижних конечностей', 'Эмболия и тромбоз артерий нижних конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (374, 'I74.4', 'Эмболия и тромбоз артерий конечностей неуточненных', 'Эмболия и тромбоз артерий конечностей неуточненных', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (375, 'I74.5', 'Эмболия и тромбоз подвздошной артерии', 'Эмболия и тромбоз подвздошной артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (376, 'I74.8', 'Эмболия и тромбоз других артерий', 'Эмболия и тромбоз других артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (377, 'I74.9', 'Эмболия и тромбоз неуточненных артерий', 'Эмболия и тромбоз неуточненных артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (378, 'I77', 'Другие поражения артерий и артериол', 'Другие поражения артерий и артериол', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (379, 'I77.0', 'Артериовенозный свищ приобретенный', 'Артериовенозный свищ приобретенный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (380, 'I77.1', 'Сужение артерий', 'Сужение артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (381, 'I77.2', 'Разрыв артерии', 'Разрыв артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (382, 'I77.3', 'Мышечная и соединительнотканная дисплазия артерий', 'Мышечная и соединительнотканная дисплазия артерий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (383, 'I77.4', 'Синдром компрессии чревного ствола брюшной аорты', 'Синдром компрессии чревного ствола брюшной аорты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (384, 'I77.5', 'Некроз артерии', 'Некроз артерии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (385, 'I77.6', 'Артериит неуточненный', 'Артериит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (386, 'I77.8', 'Другие уточненные изменения артерий и артериол', 'Другие уточненные изменения артерий и артериол', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (387, 'I77.9', 'Изменение артерий и артериол неуточненное', 'Изменение артерий и артериол неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (388, 'I78', 'Болезни капилляров', 'Болезни капилляров', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (389, 'I78.0', 'Наследственная геморрагическая телеангиэктазия', 'Наследственная геморрагическая телеангиэктазия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (390, 'I78.1', 'Невус неопухолевый', 'Невус неопухолевый', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (391, 'I78.8', 'Другие болезни капилляров', 'Другие болезни капилляров', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (392, 'I78.9', 'Болезнь капилляров неуточненная', 'Болезнь капилляров неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (393, 'I79', 'Поражения артерий, артериол и капилляров при болезнях, классифицированных в других рубриках', 'Поражения артерий, артериол и капилляров при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (394, 'I79.0', 'Аневризма аорты при болезнях, классифицированных в других рубриках', 'Аневризма аорты при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (395, 'I79.1', 'Аортит при болезнях, классифицированных в других рубриках', 'Аортит при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (396, 'I79.2', 'Периферическая ангиопатия при болезнях, классифицированных в других рубриках', 'Периферическая ангиопатия при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (397, 'I79.8', 'Другие поражения артерий, артериол и капилляров при болезнях, классифицированных в других рубриках', 'Другие поражения артерий, артериол и капилляров при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (398, 'I80', 'Флебит и тромбофлебит', 'Флебит и тромбофлебит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (399, 'I80-I89', 'БОЛЕЗНИ ВЕН, ЛИМФАТИЧЕСКИХ СОСУДОВ И ЛИМФАТИЧЕСКИХ УЗЛОВ, НЕ КЛАССИФИЦИРОВАННЫЕ В ДРУГИХ РУБРИКАХ (I', 'БОЛЕЗНИ ВЕН, ЛИМФАТИЧЕСКИХ СОСУДОВ И ЛИМФАТИЧЕСКИХ УЗЛОВ, НЕ КЛАССИФИЦИРОВАННЫЕ В ДРУГИХ РУБРИКАХ (I80-I89)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (400, 'I80.0', 'Флебит и тромбофлебит поверхностных сосудов нижних конечностей', 'Флебит и тромбофлебит поверхностных сосудов нижних конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (401, 'I80.1', 'Флебит и тромбофлебит бедренной вены', 'Флебит и тромбофлебит бедренной вены', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (402, 'I80.2', 'Флебит и тромбофлебит других глубоких сосудов нижних конечностей', 'Флебит и тромбофлебит других глубоких сосудов нижних конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (403, 'I80.3', 'Флебит и тромбофлебит нижних конечностей неуточненный', 'Флебит и тромбофлебит нижних конечностей неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (404, 'I80.8', 'Флебит и тромбофлебит других локализаций', 'Флебит и тромбофлебит других локализаций', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (405, 'I80.9', 'Флебит и тромбофлебит неуточненной локализации', 'Флебит и тромбофлебит неуточненной локализации', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (406, 'I81', 'Тромбоз портальной вены', 'Тромбоз портальной вены', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (407, 'I82', 'Эмболия и тромбоз других вен', 'Эмболия и тромбоз других вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (408, 'I82.0', 'Синдром Бадда-Киари', 'Синдром Бадда-Киари', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (409, 'I82.1', 'Тромбофлебит мигрирующий', 'Тромбофлебит мигрирующий', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (410, 'I82.2', 'Эмболия и тромбоз полой вены', 'Эмболия и тромбоз полой вены', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (411, 'I82.3', 'Эмболия и тромбоз почечной вены', 'Эмболия и тромбоз почечной вены', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (412, 'I82.8', 'Эмболия и тромбоз других уточненных вен', 'Эмболия и тромбоз других уточненных вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (413, 'I82.9', 'Эмболия и тромбоз неуточненной вены', 'Эмболия и тромбоз неуточненной вены', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (414, 'I83', 'Варикозное расширение вен нижних конечностей', 'Варикозное расширение вен нижних конечностей', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (415, 'I83.0', 'Варикозное расширение вен нижних конечностей с язвой', 'Варикозное расширение вен нижних конечностей с язвой', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (416, 'I83.1', 'Варикозное расширение вен нижних конечностей с воспалением', 'Варикозное расширение вен нижних конечностей с воспалением', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (417, 'I83.2', 'Варикозное расширение вен нижних конечностей с язвой и воспалением', 'Варикозное расширение вен нижних конечностей с язвой и воспалением', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (418, 'I83.9', 'Варикозное расширение вен нижних конечностей без язвы или воспаления', 'Варикозное расширение вен нижних конечностей без язвы или воспаления', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (419, 'I85', 'Варикозное расширение вен пищевода', 'Варикозное расширение вен пищевода', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (420, 'I85.0', 'Варикозное расширение вен пищевода с кровотечением', 'Варикозное расширение вен пищевода с кровотечением', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (421, 'I85.9', 'Варикозное расширение вен пищевода без кровотечения', 'Варикозное расширение вен пищевода без кровотечения', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (422, 'I86', 'Варикозное расширение вен других локализаций', 'Варикозное расширение вен других локализаций', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (423, 'I86.0', 'Варикозное расширение подъязычных вен', 'Варикозное расширение подъязычных вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (424, 'I86.1', 'Варикозное расширение вен мошонки', 'Варикозное расширение вен мошонки', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (425, 'I86.2', 'Варикозное расширение вен таза', 'Варикозное расширение вен таза', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (426, 'I86.3', 'Варикозное расширение вен вульвы', 'Варикозное расширение вен вульвы', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (427, 'I86.4', 'Варикозное расширение вен желудка', 'Варикозное расширение вен желудка', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (428, 'I86.8', 'Варикозное расширение вен других уточненных локализаций', 'Варикозное расширение вен других уточненных локализаций', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (429, 'I87', 'Другие поражения вен', 'Другие поражения вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (430, 'I87.0', 'Посттромботический синдром', 'Посттромботический синдром', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (431, 'I87.1', 'Сдавление вен', 'Сдавление вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (432, 'I87.2', 'Венозная недостаточность (хроническая) (периферическая)', 'Венозная недостаточность (хроническая) (периферическая)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (433, 'I87.8', 'Другие уточненные поражения вен', 'Другие уточненные поражения вен', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (434, 'I87.9', 'Поражение вены неуточненное', 'Поражение вены неуточненное', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (435, 'I88', 'Неспецифический лимфаденит', 'Неспецифический лимфаденит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (436, 'I88.0', 'Неспецифический брыжеечный лимфаденит', 'Неспецифический брыжеечный лимфаденит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (437, 'I88.1', 'Хронический лимфаденит, кроме брыжеечного', 'Хронический лимфаденит, кроме брыжеечного', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (438, 'I88.8', 'Другие неспецифические лимфадениты', 'Другие неспецифические лимфадениты', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (439, 'I88.9', 'Неспецифический лимфаденит неуточненный', 'Неспецифический лимфаденит неуточненный', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (440, 'I89', 'Другие неинфекционные болезни лимфатических сосудов и лимфатических узлов', 'Другие неинфекционные болезни лимфатических сосудов и лимфатических узлов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (441, 'I89.0', 'Лимфоотек, не классифицированный в других рубриках', 'Лимфоотек, не классифицированный в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (442, 'I89.1', 'Лимфангит', 'Лимфангит', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (91, 'I24', 'Другие формы острой ишемической болезни сердца', 'Другие формы острой ишемической болезни сердца', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (443, 'I89.8', 'Другие уточненные неинфекционные болезни лимфатических сосудов и лимфатических узлов', 'Другие уточненные неинфекционные болезни лимфатических сосудов и лимфатических узлов', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (444, 'I89.9', 'Неинфекционная болезнь лимфатических сосудов и лимфатических узлов неуточненная', 'Неинфекционная болезнь лимфатических сосудов и лимфатических узлов неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (445, 'I95', 'Гипотензия', 'Гипотензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (446, 'I95-I99', 'ДРУГИЕ И НЕУТОЧНЕННЫЕ БОЛЕЗНИ СИСТЕМЫ КРОВООБРАЩЕНИЯ (I95-I99)', 'ДРУГИЕ И НЕУТОЧНЕННЫЕ БОЛЕЗНИ СИСТЕМЫ КРОВООБРАЩЕНИЯ (I95-I99)', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (447, 'I95.0', 'Идиопатическая гипотензия', 'Идиопатическая гипотензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (448, 'I95.1', 'Ортостатическая гипотензия', 'Ортостатическая гипотензия', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (449, 'I95.2', 'Гипотензия, вызванная лекарственными средствами', 'Гипотензия, вызванная лекарственными средствами', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (450, 'I95.8', 'Другие виды гипотензии', 'Другие виды гипотензии', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (451, 'I95.9', 'Гипотензия неуточненная', 'Гипотензия неуточненная', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (452, 'I97', 'Нарушения системы кровообращения после медицинских процедур, не классифицированные в других рубриках', 'Нарушения системы кровообращения после медицинских процедур, не классифицированные в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (453, 'I97.0', 'Посткардиотомический синдром', 'Посткардиотомический синдром', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (454, 'I97.1', 'Другие функциональные нарушения после операций на сердце', 'Другие функциональные нарушения после операций на сердце', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (455, 'I97.2', 'Синдром постмастэктомического лимфатического отека', 'Синдром постмастэктомического лимфатического отека', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (456, 'I97.8', 'Другие нарушения системы кровообращения после медицинских процедур, не классифицированные в других р', 'Другие нарушения системы кровообращения после медицинских процедур, не классифицированные в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (457, 'I97.9', 'Нарушения системы кровообращения после медицинских процедур неуточненные', 'Нарушения системы кровообращения после медицинских процедур неуточненные', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (458, 'I98', 'Другие нарушения системы кровообращения при болезнях, классифицированных в других рубриках', 'Другие нарушения системы кровообращения при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (459, 'I98.0', 'Сифилис сердечно-сосудистой системы', 'Сифилис сердечно-сосудистой системы', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (460, 'I98.1', 'Поражение сердечно-сосудистой системы при других инфекционных и паразитарных болезнях, классифициров', 'Поражение сердечно-сосудистой системы при других инфекционных и паразитарных болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (461, 'I98.2', 'Варикозное расширение вен пищевода без кровотечения при болезнях, классифицированных в других рубрик', 'Варикозное расширение вен пищевода без кровотечения при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (462, 'I98.3', 'Варикозное расширение вен пищевода с кровотечением при болезнях, классифицированных в других рубрика', 'Варикозное расширение вен пищевода с кровотечением при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (463, 'I98.8', 'Другие уточненные нарушения системы кровообращения при болезнях, классифицированных в других рубрика', 'Другие уточненные нарушения системы кровообращения при болезнях, классифицированных в других рубриках', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (464, 'I99', 'Другие и неуточненные нарушения системы кровообращения', 'Другие и неуточненные нарушения системы кровообращения', null);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (66, 'I20.0', 'Нестабильная стенокардия', 'Нестабильная стенокардия', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (93, 'I24.1', 'Синдром Дресслера', 'Синдром Дресслера', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (92, 'I24.0', 'Коронарный тромбоз, не приводящий к инфаркту миокарда', 'Коронарный тромбоз, не приводящий к инфаркту миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (95, 'I24.9', 'Острая ишемическая болезнь сердца неуточненная', 'Острая ишемическая болезнь сердца неуточненная', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (94, 'I24.8', 'Другие формы острой ишемической болезни сердца', 'Другие формы острой ишемической болезни сердца', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (89, 'I23.6', 'Тромбоз предсердия, ушка предсердия и желудочка сердца как текущее осложнение острого инфаркта миока', 'Тромбоз предсердия, ушка предсердия и желудочка сердца как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (88, 'I23.5', 'Разрыв сосочковой мышцы как текущее осложнение острого инфаркта миокарда', 'Разрыв сосочковой мышцы как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (90, 'I23.8', 'Другие текущие осложнения острого инфаркта миокарда', 'Другие текущие осложнения острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (85, 'I23.2', 'Дефект межжелудочковой перегородки как текущее осложнение острого инфаркта миокарда', 'Дефект межжелудочковой перегородки как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (84, 'I23.1', 'Дефект межпредсердной перегородки как текущее осложнение острого инфаркта миокарда', 'Дефект межпредсердной перегородки как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (87, 'I23.4', 'Разрыв сухожильной хорды как текущее осложнение острого инфаркта миокарда', 'Разрыв сухожильной хорды как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (86, 'I23.3', 'Разрыв сердечной стенки без гемоперикарда как текущее осложнение острого инфаркта миокарда', 'Разрыв сердечной стенки без гемоперикарда как текущее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (81, 'I22.9', 'Повторный инфаркт миокарда неуточненной локализации', 'Повторный инфаркт миокарда неуточненной локализации', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (80, 'I22.8', 'Повторный инфаркт миокарда другой уточненной локализации', 'Повторный инфаркт миокарда другой уточненной локализации', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (83, 'I23.0', 'Гемоперикард как ближайшее осложнение острого инфаркта миокарда', 'Гемоперикард как ближайшее осложнение острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (82, 'I23', 'Некоторые текущие осложнения острого инфаркта миокарда', 'Некоторые текущие осложнения острого инфаркта миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (77, 'I22', 'Повторный инфаркт миокарда', 'Повторный инфаркт миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (76, 'I21.9', 'Острый инфаркт миокарда неуточненный', 'Острый инфаркт миокарда неуточненный', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (79, 'I22.1', 'Повторный инфаркт нижней стенки миокарда', 'Повторный инфаркт нижней стенки миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (78, 'I22.0', 'Повторный инфаркт передней стенки миокарда', 'Повторный инфаркт передней стенки миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (73, 'I21.2', 'Острый трансмуральный инфаркт миокарда других уточненных локализаций', 'Острый трансмуральный инфаркт миокарда других уточненных локализаций', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (72, 'I21.1', 'Острый трансмуральный инфаркт нижней стенки миокарда', 'Острый трансмуральный инфаркт нижней стенки миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (75, 'I21.4', 'Острый субэндокардиальный инфаркт миокарда', 'Острый субэндокардиальный инфаркт миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (74, 'I21.3', 'Острый трансмуральный инфаркт миокарда неуточненной локализации', 'Острый трансмуральный инфаркт миокарда неуточненной локализации', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (71, 'I21.0', 'Острый трансмуральный инфаркт передней стенки миокарда', 'Острый трансмуральный инфаркт передней стенки миокарда', 1);
INSERT INTO public.exp_mkb10 (id, kodmkb, name_sh, name_mkb10, enable) VALUES (70, 'I21', 'Острый инфаркт миокарда', 'Острый инфаркт миокарда', 1);