create view exp_view_usl_check(id, vid, check_all) as
SELECT exp_sluch.id,
       exp_krit_str.vid,
       exp_result.status AS check_all
FROM exp_sluch
         LEFT JOIN exp_result ON exp_result.id_sluch = exp_sluch.id
         LEFT JOIN exp_krit_str ON exp_krit_str.id = exp_result.id_krit_str::numeric;

alter table exp_view_usl_check
    owner to exp_user;

INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'Осмотр кардиолога не позднее 5 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (29, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (30, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (31, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (32, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (33, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (34, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'ЭКГ 10 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'Тропонины или креатинкиназа в крови', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'Ингибиторы агрегации тромбоцитов', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'Ацетилсалициловая кислота', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'Гиполипидемические препараты', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (35, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (23, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'Осмотр кардиолога не позднее 5 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (5, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'Ингибиторы агрегации тромбоцитов', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'Ацетилсалициловая кислота', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (25, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'ЭКГ 10 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'Осмотр кардиолога не позднее 5 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (22, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'Осмотр кардиолога не позднее 5 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (1, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (2, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (3, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (4, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (6, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (7, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'ЭКГ 10 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'Гиполипидемические препараты', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (8, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (9, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'Ингибиторы агрегации тромбоцитов', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'Ацетилсалициловая кислота', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (10, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (11, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (12, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (13, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (14, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (15, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (16, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (17, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'Ингибиторы агрегации тромбоцитов', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'Ацетилсалициловая кислота', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (18, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (19, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (20, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (21, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (24, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Электрокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Клинический анализ крови', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Биохимия кровиКреатининГлюкозаКреатинкиназа', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Анализ крови по оценке нарушений липидного обмена биохимический', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Эхокардиография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Дуплексное сканироваие брахиоцефальных артерий', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Коронарография', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Терапия лекарственными препаратами', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (26, 'Бета-адреноблокаторы, блокаторы кальциевых каналов, нитратыЭндоваскулярные методы', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'ЭКГ 10 минут от поступления', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'Тропонины или креатинкиназа в крови', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'Ингибиторы агрегации тромбоцитов', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (27, 'ЭКГ час до операцииЭКГ час до операции', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'Осмотр кардиолога не позднее 5 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'ЭКГ 10 минут от поступления', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'Тропонины или креатинкиназа в крови', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'Ингибиторы агрегации тромбоцитов', 1);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'Ацетилсалициловая кислота', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'Гиполипидемические препараты', 0);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'ФибринолитикиКоронарное вмешательство', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'ЭКГ час до тромболитической терапииЭКГ час после тромболитической терапии', 2);
INSERT INTO public.exp_view_usl_check (id, vid, check_all) VALUES (28, 'ЭКГ час до операцииЭКГ час до операции', 2);